Repository pickly-team/pickly-frontend, pull requests merged in 2023-05, with the labels that each got.

#74 feat: 토스트 UI 컴포넌트 추가
  .storybook/preview-head.html
  index.html
  src/App.tsx
  src/common-ui/Toast/Toast.stories.tsx
  src/common-ui/Toast/Toast.tsx
  src/common-ui/Toast/ToastList.tsx
  src/common-ui/Toast/hooks/useToast.tsx
  src/store/toast.ts
  src/styles/theme.ts
Labels: ✨ Feature, 😎 Self-Approve, 🎨 Style

#76 [FEAT] 알림 리스트 페이지
  src/App.tsx
  src/common-ui/BottomNavigation.tsx
  src/common-ui/Header/Header.tsx
  src/common-ui/Layout.tsx
  src/common-ui/SlideItem.tsx
  src/common-ui/utils/skeletonAnimations.ts
  src/common-ui/utils/skeletonStyles.ts
  src/constants/navigatePath.ts
  src/constants/queryKeys.ts
  src/notification/api/notification.ts
  src/notification/ui/NotificationSkeletonItem.tsx
  src/notification/ui/Notifications.tsx
  src/notification/ui/skeleton/NotificationSlideItem.tsx
  src/pages/NotificationPage.tsx
  src/styles/GlobalStyle.tsx
  src/utils/date/formatDateByStartAndEnd.test.ts
  src/utils/date/formatDateByStartAndEnd.ts
  src/utils/getRandomElementFromArray.ts
  src/utils/resolveAfterDelay.ts
Labels: feature

#80 feat: 카테고리 목록 페이지 추가
  package.json
  src/App.tsx
  src/category/api/category.ts
  src/category/index.d.ts
  src/category/service/hooks/useCategoryMode.tsx
  src/category/ui/Add/CategoryAddArea.tsx
  src/category/ui/Add/CategoryManageInfo.tsx
  src/category/ui/Add/CategoryName.tsx
  src/category/ui/CategoryList.tsx
  src/category/ui/SkeletonCategoryList.tsx
  src/common-ui/BottomNavigation.tsx
  src/common-ui/BottomSheet/TriggerBottomSheet.tsx
  src/common/ui/BSConfirmation.tsx
  src/common/ui/DragAndDrop.tsx
  src/common/ui/IconButton.tsx
  src/common/ui/ListItem.tsx
  src/constants/navigatePath.ts
  src/members/ui/StatsBox.tsx
  src/pages/CategoryListPage.tsx
  src/pages/CategoryManagePage.tsx
  yarn.lock
Labels: ✨ Feature, feature

#64 feat : FAQ 페이지
  src/App.tsx
  src/common-ui/Collapsible.tsx
  src/constants/navigatePath.ts
  src/pages/FaqPage.tsx
Labels: ✨ Feature

#62 feat : 좋아요 목록 페이지
  src/App.tsx
  src/bookmarks/api/like.ts
  src/bookmarks/ui/BookmarkLikeButton.tsx
  src/bookmarks/ui/Like/BookmarkLikeButton.tsx
  src/bookmarks/ui/Like/BookmarkLikeItem.tsx
  src/bookmarks/ui/Like/BookmarkLikeList.tsx
  src/bookmarks/ui/Like/SkeletonBookmarkLikeList.tsx
  src/bookmarks/ui/Main/BookmarkItem.tsx
  src/common/service/hooks/useBottomIntersection.ts
  src/constants/navigatePath.ts
  src/pages/BookMarkDetailPage.tsx
  src/pages/LikePage.tsx
Labels: feature

#86 build: vercel Analytics 추가
  package.json
  src/App.tsx
  yarn.lock
Labels: 🔨 Fix, 😎 Self-Approve

#83 feat: 카테고리 API 연동
  src/bookmarks/api/bookmark.ts
  src/bookmarks/service/hooks/add/useCategoryList.tsx
  src/bookmarks/service/hooks/home/useBookmarkList.tsx
  src/bookmarks/service/hooks/home/useCategory.tsx
  src/bookmarks/service/hooks/home/useDeleteBookmarkList.tsx
  src/bookmarks/ui/BookmarkTagList.tsx
  src/bookmarks/ui/Main/BookmarkToggle.tsx
  src/category/api/add.ts
  src/category/api/category.ts
  src/category/api/delete.ts
  src/category/api/edit.ts
  src/category/api/order.ts
  src/category/index.d.ts
  src/category/service/hooks/useAddAndDeleteCategory.tsx
  src/category/service/hooks/useCategoryMode.tsx
  src/category/service/hooks/useEditCategory.tsx
  src/category/ui/Add/CategoryAddArea.tsx
  src/category/ui/CategoryList.tsx
  src/category/ui/SkeletonCategoryList.tsx
  src/common-ui/BottomNavigation.test.tsx
  src/common/service/client.ts
  src/pages/CategoryListPage.tsx
  src/pages/CategoryManagePage.tsx
  src/pages/MainPage.tsx
Labels: ✨ Feature, feature
