Repository pickly-team/pickly-frontend, pull requests merged in 2023-03, with the labels that each got.

#20 [FEATURE] BottomNavigation 컴포넌트, Toggle 컴포넌트, Input 컴포넌트 추가
  src/common-ui/BottomNavigation.test.tsx
  src/common-ui/BottomNavigation.tsx
  src/common-ui/Button.tsx
  src/common-ui/Input.test.tsx
  src/common-ui/Input.tsx
  src/common-ui/Text.test.tsx
  src/common-ui/Text.tsx
  src/common-ui/Toggle.test.tsx
  src/common-ui/Toggle.tsx
  src/common-ui/assets/Icon.tsx
  src/common-ui/assets/IconLoader.tsx
  src/config/navigatePath.ts
  src/styles/GlobalStyle.tsx
  src/styles/theme.ts
Labels: 🔨 Fix, ✨ Feature, ✅ Test

#25 [FIX] Checkbox 테스트 깨지는 것 수정
  src/common-ui/CheckBox.test.tsx
Labels: fix

#30 Feature/common UI/bottom sheet
  .storybook/main.js
  jest.config.js
  package.json
  src/common-ui/BottomSheet/BottomSheet.stories.tsx
  src/common-ui/BottomSheet/BottomSheet.test.tsx
  src/common-ui/BottomSheet/BottomSheet.tsx
  src/common-ui/BottomSheet/style.module.css
  src/main.tsx
  yarn.lock
Labels: ✨ Feature, ✅ Test, ⚙️ Lib

#38 [FEATURE] 메인 페이지 작업
  package.json
  src/App.tsx
  src/bookmarks/api/bookmark.ts
  src/bookmarks/service/hooks/useBookMarkHandler.tsx
  src/bookmarks/ui/BSDeleteComfirmation.tsx
  src/bookmarks/ui/BookmarkItem.tsx
  src/bookmarks/ui/EditBookmarkItem.tsx
  src/bookmarks/ui/ToggleHandler.tsx
  src/bookmarks/ui/UserInfo.tsx
  src/common-ui/BottomNavigation.tsx
  src/common-ui/BottomSheet/style.module.css
  src/common-ui/Button.tsx
  src/common-ui/Select/Select.tsx
  src/common-ui/Text.tsx
  src/pages/MainPage.tsx
  src/styles/theme.ts
  yarn.lock
Labels: ✨ Feature, feature

#34 [FEATURE] 북마크 상세페이지 컴포넌트 작성
  .gitignore
  index.html
  src/App.tsx
  src/bookmarks/ui/BookMarkArticle.tsx
  src/bookmarks/ui/BookMarkLikeButton.tsx
  src/comment/ui/CommentCountInfo.tsx
  src/comment/ui/CommentItem.tsx
  src/comment/ui/CommentUploadInput.tsx
  src/comment/ui/CommetBottomSheet.tsx
  src/common-ui/BottomNavigation.tsx
  src/common-ui/BottomSheet/BottomSheet.tsx
  src/common-ui/BottomSheet/hooks/useBottomSheet.ts
  src/common-ui/Header/Header.test.tsx
  src/common-ui/Header/Header.tsx
  src/common-ui/Layout.tsx
  src/common-ui/Text.tsx
  src/common-ui/assets/Icon.tsx
  src/common-ui/assets/IconLoader.tsx
  src/components/Bear.tsx
  src/components/Button.stories.tsx
  src/constants/navigatePath.ts
  src/constants/zIndex.ts
  src/pages/BookMarkDetailPage.tsx
  src/utils/getRem.test.ts
  src/utils/getRem.ts
  vercel.json
  yarn.lock
Labels: ✨ Feature

#42 [STYLE] 사용되는 아이콘 모두 추가
  .storybook/main.js
  .storybook/preview.jsx
  package.json
  src/common-ui/assets/Icon.stories.mdx
  src/common-ui/assets/Icon.tsx
  src/common-ui/assets/IconLoader.tsx
  yarn.lock
Labels: 🎨 Style, style

#45 [FIX]: 아이콘 네이밍 변경에 따른 오류 수정
  src/bookmarks/ui/BookMarkArticle.tsx
  src/bookmarks/ui/BookMarkLikeButton.tsx
  src/comment/ui/CommentItem.tsx
  src/comment/ui/CommentUploadInput.tsx
  src/common-ui/Header/Header.test.tsx
  src/common-ui/Header/Header.tsx
Labels: 🔨 Fix

#49 [FIX] Github Action 에서 jest coverage action 제거
  .github/workflows/pr-deploy.yml
Labels: 😎 Self-Approve, fix
