Repository pickly-team/pickly-frontend, pull requests merged in 2023-06, with the labels that each got.

#87 Feat/i82/friends list
  package.json
  src/App.tsx
  src/common/service/client.ts
  src/constants/navigatePath.ts
  src/constants/queryKeys.ts
  src/friend/api/friends.tsx
  src/friend/ui/FriendSkeletonItem.tsx
  src/friend/ui/FriendTypeSelect.tsx
  src/friend/ui/Friends.tsx
  src/friend/ui/buttons/FollowButton.tsx
  src/friend/ui/buttons/UnFollowButton.tsx
  src/friend/ui/friend/FriendFollowerItem.tsx
  src/friend/ui/friend/FriendFollowingItem.tsx
  src/friend/ui/friend/layout/FriendItemLayout.tsx
  src/pages/FriendPage.tsx
  src/utils/decodeEmojiBase64.test.ts
  src/utils/decodeEmojiBase64.ts
  yarn.lock
Labels: feature

#99 fix: paramsSerializer의 타입 오류 수정
  src/bookmarks/api/bookmark.ts
  src/category/api/delete.ts
Labels: 🐛 Bug, fix

#84 feat : 멤버 Comment List 페이지 추가
  src/App.tsx
  src/comment/api/Comment.ts
  src/comment/ui/bookmark/CommentCountInfo.tsx
  src/comment/ui/bookmark/CommentItem.tsx
  src/comment/ui/bookmark/CommentUploadInput.tsx
  src/comment/ui/bookmark/CommetBottomSheet.tsx
  src/comment/ui/comment-list/CommentItem.tsx
  src/constants/navigatePath.ts
  src/pages/BookMarkDetailPage.tsx
  src/pages/CommentPage.tsx
Labels: ✨ Feature, feature
