Repository pickly-team/pickly-frontend, pull requests merged in 2023-07, with the labels that each got.

#108 fix: array params 형식에 대해 qs 라이브러리를 이용한 방식으로 변경
  src/bookmarks/api/bookmark.ts
  src/category/api/delete.ts
Labels: 🐛 Bug, fix

#110 setting: storybook deploy cd 임시 제거
  .github/workflows/storybook-deploy.yml
Labels: 🛠 Setting

#113 feat: select 바깥 영역을 클릭하면 닫히도록 로직 추가
  src/common-ui/Select/Select.tsx
Labels: 🐛 Bug, fix

#123 feat: 아이템 삭제에 대한 toast 추가
  src/bookmarks/api/bookmark.ts
  src/category/api/delete.ts
Labels: ✨ Feature

#130 fix: 카테고리 수정 페이지 누락 추가
  src/App.tsx
Labels: 🐛 Bug, fix

#134 fix: 임시로 사용되던 id 실제 memberId로 변경
  src/bookmarks/service/hooks/add/useCategoryList.tsx
  src/bookmarks/ui/Like/BookmarkLikeList.tsx
  src/category/ui/CategoryList.tsx
  src/common-ui/BottomNavigation.tsx
  src/pages/CategoryListPage.tsx
  src/pages/CategoryManagePage.tsx
  src/pages/CommentPage.tsx
Labels: 🔨 Fix, fix

#138 fix: api 수정에 따른 mapper 로직 삭제 및 반영
  src/notification/api/notification.ts
Labels: 🔨 Fix

#141 fix: 알림 기준 생성 API 삭제
  src/RNListener.tsx
  src/members/api/member.ts
Labels: 🔨 Fix, fix

#152 fix: 댓글 사용자 다르게 나오던 오류 수정
  src/comment/ui/bookmark/CommentList.tsx
Labels: 🔨 Fix, 🐛 Bug

#160 fix: 유저 신고하기 기능 삭제
  src/pages/FriendBookmarkPage.tsx
Labels: 🔨 Fix

#162 fix: 내 포스트가 아니면 좋아요/해제 누를 수 없도록 설정
  src/bookmarks/ui/BookmarkArticle.tsx
  src/bookmarks/ui/Like/BookmarkLikeButton.tsx
Labels: 🔨 Fix, 🐛 Bug

#170 fix: 친구 리스트 페이지 닉네임 제대로 출력되지 않는 오류 수정
  src/friend/api/friends.tsx
  src/friend/ui/Friends.tsx
Labels: 🔨 Fix, 🐛 Bug

#177 fix: backdrop 추가하여 클릭하면 이모지 설정 BS 닫히도록 수정
  src/common/service/useChangeEmoji.tsx
  src/common/ui/Emoji.tsx
  src/pages/UserInfoPage.tsx
  src/user/ui/UserProfileInfo.tsx
Labels: 🐛 Bug, 🎨 Style

#180 fix: 북마크 상세 페이지 좋아요/해제를 하더라도 메인 화면 리스트에 반영되지 않던 오류 수정
  src/bookmarks/api/bookmark.ts
Labels: 🔨 Fix, 🐛 Bug

#182 fix: 알림 페이지에서 알림을 끄더라도 반영되지 않던 오류 수정
  src/members/ui/NotificationSettingBox.tsx
Labels: 🔨 Fix, 🐛 Bug

#186 fix: 웹뷰 snap 뒤로가기 이벤트에 대해 title, url 초기화 되지 않던 오류 수정
  src/RNListener.tsx
  src/common/service/hooks/useBridgeCallback.ts
Labels: 🔨 Fix, 🐛 Bug

#190 fix: 북마크 추가/삭제에 대해서 멤버 프로필 업데이트 되도록 수정
  src/bookmarks/api/bookmark.ts
Labels: 🔨 Fix, 🐛 Bug

#199 fix: 기본 설정 이모지 추가
  src/auth/api/profile.ts
Labels: 🔨 Fix

#202 [FIX] 댓글리스트 내, 북마크 조회시 북마크 id의 맵핑작업을 재진행합니다.
  src/comment/api/Comment.ts
  src/comment/ui/comment-list/CommentItem.tsx
  src/pages/CommentPage.tsx
Labels: 🔨 Fix, 🐛 Bug

#206 fix: 댓글에 대한 권한이 이상하던 오류 수정
  src/bookmarks/api/bookmark.ts
  src/comment/api/Comment.ts
  src/comment/ui/bookmark/CommentList.tsx
  src/comment/ui/bookmark/CommentUploadInput.tsx
Labels: 🔨 Fix, 🐛 Bug

#211 feat: 문의하기 기능에 대한 임시 토스트 추가
  src/members/ui/CustomerFeedbackBox.tsx
  src/store/toast.ts
Labels: ✨ Feature

#219 fix: url 입력이 제대로 되지 않던 오류 수정
  src/bookmarks/service/hooks/add/useInputUrl.tsx
  src/common-ui/BottomNavigation.tsx
Labels: 🔨 Fix, 🐛 Bug

#224 feat: 댓글 신고하기 API 실제 연동
  src/bookmarks/api/bookmark.ts
  src/comment/api/Comment.ts
Labels: ✨ Feature
